name: Veracode Auto-Packaging and Scan

on:
  push:
    branches:
      - main  # Change branch if needed
  pull_request:

jobs:
  veracode-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Veracode CLI and Package Scan
        run: |
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode package -das ${{ github.workspace }} --output ./verascan

          # Check if the verascan directory exists
          if [ ! -d "verascan" ]; then
            echo "Error: verascan directory not found."
            exit 1
          fi

      # - name: Upload Verascan Artifact (Optional)
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: VeracodeScanResults
      #     path: verascan

      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.7
        with:
            appname: 'Recent'
            createprofile: false
            filepath: './verascan'
            version: ${{ github.run_id }}
            vid: '${{ secrets.VID }}'
            vkey: '${{ secrets.VKEY }}'
            # createsandbox: 'false'
            # sandboxname: 'SANDBOXNAME'
            scantimeout: 120
            # exclude: '*.js'
            # include: '*.war'
            criticality: 'VeryHigh'
            deleteincompletescan: 0
